"""
BASALT-Air: A modular metagenomic binning and refinement pipeline.

This package exposes a CLI entry point (the ``basalt`` console script,
generated by ``setuptools`` from :func:`basalt.cli.main`) and a number of
internal modules implementing individual steps of the pipeline (autobinning,
dereplication, outlier removal, contig retrieval, reassembly, and model
utilities).

Typical users should invoke BASALT-Air via the command-line script
``basalt`` rather than importing these internals directly.
"""

__version__ = "1.0.0"
__all__ = ["__version__"]
